# Generated by Django 5.0.3 on 2024-04-03 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecartapp", "0003_cart"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="pid",
            field=models.ForeignKey(
                db_column="pid",
                on_delete=django.db.models.deletion.CASCADE,
                to="ecartapp.product",
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="uid",
            field=models.ForeignKey(
                db_column="uid",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
