# Generated by Django 5.0.3 on 2024-04-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecartapp", "0004_alter_cart_pid_alter_cart_uid"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="qty",
            field=models.IntegerField(default=1),
        ),
    ]
